
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable node js
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - nodejs
      - mysql

  - name: add user ExpenseApp
    ansible.builtin.user:
      name: expense 

  - name: import tasks from common role
    ansible.builtin.import_role:
      name: common
      tasks_from: main.yaml

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy file 
    ansible.builtin.template:
      src: backend.service.j2
      dest: /etc/systemd/system/backend.service

  - name: ansible to install pymysql
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9

  
  - name: Try to create database as root/nopassword first. If not allowed, pass the credentials
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      target: /app/schema/backend.sql
      name: all
      state: import

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
      state: restarted
      name: backend
